language: python
python:
- '2.7'
- '3.5'
- '3.6'
#os:
#  - linux
#  - osx
env:
  global:
  - CC_TEST_REPORTER_ID=60ef418b01ff3218f7473f7a20f98bc3299e718f8bdfacdf84e4c8e41eca1db7
cache: pip
install:
- pip install --upgrade coverage setuptools requests
- chmod +x ./before_deploy.sh
- source ./before_deploy.sh
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- coverage run --source=vaud setup.py test
after_script:
- coverage xml
- ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT || true
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  user: 1271
  password:
    secure: ydzw2Q+wnJ41HAlP+rPMqrMsdfJ0yBn8I2EPYnbiPllhlgTv1NnggcbCAlf8k5qKn5P1aKWPj23t1U0c474owJ1Scykdrge4iNcRKysY95ojru5yveEoURRkBehloP6yN0a0FdKNy4qMRWp6VutAKpJzQxVDTZ4kp410/pIPRrA5j/Kdxy9TByw1PiV+jJNe3/9YAxh+V6EH79wbTRvKcUwYEgxDtldxEKx/9NlwMECGHYvhIAkiFNhFck9bHU89j2mKx1LShV+YCE20rZjXQhEnbo/+ZQGyKltgAX/KV3zL/e7sELqj1pMPutcswpKp66buGG/YjzB61Y+BdmBy4i8W0bj4g4peWUfs4SITH++vOL6Wd4P9y06Qqs+y3/o3zm4q6B2j8Na4sWrXKDRxqgHlp5vNOtZAzgmOMax2DQMZfXzGDTxqpAjy0HSSjvFeuGb4IZjeM+gEM5PXbhPY2dGNuEcvj5wuJhRXqXDFJXL/bbAczFqZskzkvXpFS7O0zi2aTMAClhry+EVVykUyR3OafXzq4yFTasg9ah6nNzHvHS/YPMzfjqUUg7Uh4EyJ2TiE2C0rpL3NG/R6GHBzqLC+dqlp2ARCFNh9xVIHdZ79zTvQSewMNNJPsvGYHIHz4KeWDtbL9GxVXtkzk3+Z6wgzox45ZLdA0fCKlsTl/Wg=
  on:
    branch: master
    tags: true
    condition: "$allow_deploy == true"
